import pyttsx3

dictAI = pyttsx3.init()
dictionary_dataset = {
    "abandon": "To leave behind or give up completely.",
    "ability": "The capacity to do something.",
    "abundant": "Existing or occurring in large amounts.",
    "access": "The means of approaching or entering a place.",
    "acquire": "To gain possession of something.",
    "adapt": "To change in order to fit new conditions.",
    "advice": "Guidance or recommendations concerning future actions.",
    "affect": "To have an influence on.",
    "ambition": "A strong desire to do or achieve something.",
    "analyze": "To examine in detail for purposes of explanation.",
    "anticipate": "To expect or look ahead to something with pleasure.",
    "anxious": "Feeling or showing worry or nervousness.",
    "apparent": "Clearly visible or understood.",
    "approach": "To come near or nearer to someone or something.",
    "appropriate": "Suitable or proper in the circumstances.",
    "arrange": "To put things in a neat, attractive, or required order.",
    "assume": "To suppose to be the case, without proof.",
    "atmosphere": "The envelope of gases surrounding the earth.",
    "attempt": "To make an effort to achieve or complete something.",
    "attract": "To draw interest or attention.",
    "balance": "A condition in which different elements are equal or in the correct proportions.",
    "benefit": "An advantage or profit gained from something.",
    "brilliant": "Exceptionally clever or talented.",
    "calculate": "To determine mathematically.",
    "capacity": "The maximum amount something can contain or produce.",
    "capture": "To take control or possession of something.",
    "category": "A class or division of people or things.",
    "challenge": "A task or situation that tests someone's abilities.",
    "character": "The mental and moral qualities of an individual.",
    "circumstance": "A fact or condition connected with an event or action.",
    "clarify": "To make something less confused and more clearly comprehensible.",
    "collapse": "To fall down or cave in suddenly.",
    "combine": "To unite or merge together.",
    "comfort": "A state of physical ease and freedom from pain.",
    "communicate": "To share or exchange information or ideas.",
    "compare": "To estimate or note the similarity or dissimilarity between.",
    "compete": "To strive to gain or win something.",
    "complain": "To express dissatisfaction or annoyance.",
    "complex": "Consisting of many different and connected parts.",
    "conclude": "To bring something to an end.",
    "conflict": "A serious disagreement or argument.",
    "confuse": "To cause someone to become bewildered or perplexed.",
    "connect": "To join together so as to provide access and communication.",
    "consequence": "A result or effect of an action or condition.",
    "consider": "To think carefully about something.",
    "constant": "Occurring continuously over a period of time.",
    "construct": "To build or form by putting together parts.",
    "consume": "To use up or devour.",
    "contain": "To have or hold something within.",
    "continue": "To persist in an activity or process.",
    "control": "To have power over or direct something.",
    "convince": "To persuade someone to do or believe something.",
    "create": "To bring something into existence.",
    "culture": "The customs, arts, and achievements of a people.",
    "damage": "Physical harm that impairs the value or usefulness.",
    "decide": "To make a choice or judgment.",
    "define": "To state or describe exactly the nature or meaning of.",
    "delay": "To make someone or something late or slow.",
    "deliver": "To bring and hand over a package or message.",
    "demand": "To ask for something forcefully.",
    "demonstrate": "To show clearly and deliberately.",
    "deny": "To refuse to admit the truth or existence of something.",
    "depend": "To rely on for support or help.",
    "describe": "To give an account of something in words.",
    "design": "To create a plan or drawing to show the look of something.",
    "destroy": "To put an end to the existence of something.",
    "determine": "To establish exactly by research or calculation.",
    "develop": "To grow or cause to grow and become more mature.",
    "device": "A thing made for a particular purpose, especially a machine.",
    "differ": "To be unlike or dissimilar.",
    "difficult": "Needing much effort or skill to accomplish.",
    "direct": "To control the operations of something.",
    "disappear": "To cease to be visible.",
    "discover": "To find something unexpectedly.",
    "discuss": "To talk about something with someone.",
    "display": "To put something in a prominent place for viewing.",
    "distance": "The amount of space between two points.",
    "divide": "To separate or be separated into parts.",
    "document": "A piece of written, printed, or electronic matter.",
    "dominate": "To have power and influence over something.",
    "doubt": "A feeling of uncertainty or lack of conviction.",
    "draw": "To produce a picture by making lines.",
    "dream": "A series of thoughts or visions during sleep.",
    "drive": "To operate and control the direction of a vehicle.",
    "drop": "To let or make something fall vertically.",
    "earn": "To receive payment for work done.",
    "educate": "To give someone training and instruction.",
    "effect": "A change that is a result of an action.",
    "effort": "A vigorous or determined attempt.",
    "elect": "To choose someone for a position by voting.",
    "emerge": "To come into view or become exposed.",
    "emotion": "A strong feeling deriving from one's circumstances.",
    "emphasize": "To give special importance to something.",
    "employ": "To give work to someone and pay them for it.",
    "enable": "To give someone the means or ability to do something.",
    "encourage": "To give support or confidence to someone.",
    "engineer": "A person who designs, builds, or maintains engines or machines.",
    "enhance": "To improve the quality, amount, or strength of something.",
    "enjoy": "To take delight or pleasure in an activity.",
    "ensure": "To make certain that something happens.",
    "enter": "To come or go into a place.",
    "entire": "With no part left out; whole.",
    "environment": "The surroundings or conditions in which a person lives.",
    "establish": "To set up on a firm or permanent basis.",
    "estimate": "To roughly calculate or judge the value of something.",
    "evaluate": "To form an idea of the amount or value of something.",
    "event": "A significant occurrence or happening."
}

word = input("Input the word you are searching for: ")

if word in dictionary_dataset:
    dictAI.say(f"{word} means {dictionary_dataset[word]}")
    dictAI.runAndWait()
else:
    dictAI.say(f" The word {word} is not found")
    dictAI.runAndWait()